# Generated by Django 5.1.6 on 2025-05-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='feedback',
        ),
        migrations.AddField(
            model_name='project',
            name='project_category',
            field=models.CharField(choices=[('Database', 'Database'), ('Web Development', 'Web Development'), ('Mobile App', 'Mobile App'), ('AI/ML', 'AI/ML'), ('Networking', 'Networking'), ('Security', 'Security')], default='Database', max_length=200),
        ),
    ]
