# Generated by Django 5.1.6 on 2025-05-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayApp', '0002_remove_project_feedback_project_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='grade_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GRADED', 'Graded')], default='GRADED', max_length=20),
        ),
    ]
